# Generated by Django 4.2.30 on 2026-06-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='agreeableness_conclusions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='conscientiousness_conclusions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='extraversion_conclusions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='first_test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='highest_variance_trait',
            field=models.CharField(default='N/A', max_length=3),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='neuroticism_conclusions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='openness_conclusions',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='personalityprofile',
            name='primary_dominant_trait',
            field=models.CharField(default='N/A', max_length=3),
        ),
        migrations.AlterField(
            model_name='personalityprofile',
            name='ai_recommendation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='personalityprofile',
            name='ai_summary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='personalityprofile',
            name='ai_trends_analysis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='personalityprofile',
            name='first_test_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='personalityprofile',
            name='historical_graphics_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='personalityprofile',
            name='latest_test_scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='personalityprofile',
            name='total_tests_taken',
            field=models.IntegerField(default=0),
        ),
    ]
